# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: default
stringData:
    admin-user: ENC[AES256_GCM,data:yYpgGn7J5g==,iv:q/jYIRQI+9gfiSpG08NSR9vnafYdlSIczTuT2cjfvqk=,tag:aBo6ydoZmysymUAZKN+9BA==,type:str]
    admin-password: ENC[AES256_GCM,data:FQnwyZyWDBQcgci4APMOrKOIapx8YizAeUJJRJX2h8o0,iv:FYkvu8I7QTXo6tEy8nO4lvo5RgIHuN9Lo4ZyNaQfVkY=,tag:C4VtxDI5qpx+pXNOEZbh4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZejJNMlQrQk50ZHJYcGo1
            Y0tQRXNwR2d4eEwzeVVWL2dZaUxjVG9FSm40CmF0VjJZNHJBNW1HeWIycDV4QW9s
            ajlWaUgveWMzd1oxYnFuOFQ0Wnl5RkEKLS0tIDN3NlNPVzZGZXIySDg5TUlOb1FF
            bkNsSVh0dWhJejVWQ3pnRU53NG9TM0EKq+MAK34ITDSmnipFZ0KQ5I4qnvUXeXPI
            766LTnlnHAd2vROhfLnrHWC9mXHhqcSeDzCksevqEnYwuqnWNemvPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-15T19:57:42Z"
    mac: ENC[AES256_GCM,data:NL2ece71UDKfzs9APxWKa4enaaX2YAPVsCFXmtmKA9pDJYA/ZzA4mzh8Jjr83DXZl/KS5xgxBWuMLJjuQVbywP8bXU37l2l24WDGSU3b6phVtryWDmjsxhWXha8dfPA2Kh6fXNgykUDw2PUZBdoLqG41Va7LBFYIEUWMC0IVjdc=,iv:xpAI/msxfJlnTnhiJZu0tPL5gl+1zC4yzROcdnMq48g=,tag:zI52dxRcgdCGqIBna/9lUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: default
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:E8ot5eZG+jY=,iv:qDAKllZ8/KJwLhpqVKNOC86KdCvEOBS+btnYDOp0ho8=,tag:imSZkCQrepIArl0nwfUdkQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:Hdbk8sIVKO1fdsm/3eH1DorRl9CB/lxTkTOKW2APHD1g0eWO,iv:lgi4rJxQhWfvHtEvw/xa++dDK4H7Mz/KRDGBCPjpS20=,tag:RhhmSKaEJ3n7H5v1QonrcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZejJNMlQrQk50ZHJYcGo1
            Y0tQRXNwR2d4eEwzeVVWL2dZaUxjVG9FSm40CmF0VjJZNHJBNW1HeWIycDV4QW9s
            ajlWaUgveWMzd1oxYnFuOFQ0Wnl5RkEKLS0tIDN3NlNPVzZGZXIySDg5TUlOb1FF
            bkNsSVh0dWhJejVWQ3pnRU53NG9TM0EKq+MAK34ITDSmnipFZ0KQ5I4qnvUXeXPI
            766LTnlnHAd2vROhfLnrHWC9mXHhqcSeDzCksevqEnYwuqnWNemvPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-15T19:57:42Z"
    mac: ENC[AES256_GCM,data:NL2ece71UDKfzs9APxWKa4enaaX2YAPVsCFXmtmKA9pDJYA/ZzA4mzh8Jjr83DXZl/KS5xgxBWuMLJjuQVbywP8bXU37l2l24WDGSU3b6phVtryWDmjsxhWXha8dfPA2Kh6fXNgykUDw2PUZBdoLqG41Va7LBFYIEUWMC0IVjdc=,iv:xpAI/msxfJlnTnhiJZu0tPL5gl+1zC4yzROcdnMq48g=,tag:zI52dxRcgdCGqIBna/9lUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
