# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: default
stringData:
    admin-user: ENC[AES256_GCM,data:bVcQb4VXPA==,iv:/h7pmWLCCYeCKmQEWETXI0B0mme6gX/qCwoNREd8rKk=,tag:u9EBj7MEgEDPt3W9N34qCg==,type:str]
    admin-password: ENC[AES256_GCM,data:JTh///h5abnUJ/zGdn5hVMIzUDbmeri2XrQ/RxHZwBv+,iv:kx/E+KCXk4nYtxwTfpAx1T9AM6ghQpQ3V8OylzcwOKc=,tag:XkCRMQpsVxByeUowbZpVzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbUhmMEZOMitjMjl5cHpa
            WXFKUUp2QmJab0N6ZHYzV3o2VHlHY2hTdW1rCk83VzJQdlFlZ3BJV21SOVVvYy90
            STVNWEhqeHZnOFdwV0xsVzVIM1h0aFUKLS0tIDVoM2ptM3NlR3dIMHo4bEY1TG1M
            a1d6YzJzWFByelM0cmYwNjZKNFBTcGMKaINZdsmAH7crgIpKCbtftn+mdbG1WBRE
            /+V9hCYR62ADuiasN1gyyYtRJSssaNBtUCyk8fWWNpKgKxO1aVNMzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-29T14:24:14Z"
    mac: ENC[AES256_GCM,data:wkGSNzB5LxbixwRLKl1awdUuraXtlIcS3EXano492UeKHASb6LOdleZ7bO0C1lqwnam2PL9q8q7Reuu0s68xWzx99MYVBK4+3xvzviKyYxEZhXQK+0SzA7AlsLT3x/8Mrv5HZv07hdaPA5EtFyNmmjWGttmn2ZbOK7lk7fsitXo=,iv:nrrI8teUEu6mXPPk/t58Oc/R/uoYxMdI6UpSHoFiAls=,tag:oJwb7DC8jZP5bfmVCQPCeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: default
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:vfLX5I6lt64=,iv:2sOOw2BZGe4MYYyoNRbAYAMOg+EdGd7ozsnBHSTpipo=,tag:rOv+R2Vf//qyzOHcStzJzQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:dDNiWx4LYXJ/pvxW5OKTj47lDV3Thj+nfq++7tzbScb0qXQ8,iv:dnS4kDcgpRnuUpmD7N1feE11KAUq3SwriNBcypmoZRA=,tag:OHF6FLhsyya1p6EMqXxwrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbUhmMEZOMitjMjl5cHpa
            WXFKUUp2QmJab0N6ZHYzV3o2VHlHY2hTdW1rCk83VzJQdlFlZ3BJV21SOVVvYy90
            STVNWEhqeHZnOFdwV0xsVzVIM1h0aFUKLS0tIDVoM2ptM3NlR3dIMHo4bEY1TG1M
            a1d6YzJzWFByelM0cmYwNjZKNFBTcGMKaINZdsmAH7crgIpKCbtftn+mdbG1WBRE
            /+V9hCYR62ADuiasN1gyyYtRJSssaNBtUCyk8fWWNpKgKxO1aVNMzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-29T14:24:14Z"
    mac: ENC[AES256_GCM,data:wkGSNzB5LxbixwRLKl1awdUuraXtlIcS3EXano492UeKHASb6LOdleZ7bO0C1lqwnam2PL9q8q7Reuu0s68xWzx99MYVBK4+3xvzviKyYxEZhXQK+0SzA7AlsLT3x/8Mrv5HZv07hdaPA5EtFyNmmjWGttmn2ZbOK7lk7fsitXo=,iv:nrrI8teUEu6mXPPk/t58Oc/R/uoYxMdI6UpSHoFiAls=,tag:oJwb7DC8jZP5bfmVCQPCeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-test
    namespace: default
stringData:
    test-user: ENC[AES256_GCM,data:GLnNG4VI,iv:RnkZHTn4IWIwlxlloRhyoIL0OaS/98WiASlWfflr+uU=,tag:n6vJG7q8YIb/AbS9Ho5XkQ==,type:str]
    test-password: ENC[AES256_GCM,data:G3znVDntNIZgh2DDc96X7EaFhVLhTLDsbA7GXJIDVp5J69qRTYo=,iv:D+Jt2i2gx3EgfW7nXE0zi/0dQjEN+4tisOML7F56qWM=,tag://hU6IlqCRly42/B7tHpNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbUhmMEZOMitjMjl5cHpa
            WXFKUUp2QmJab0N6ZHYzV3o2VHlHY2hTdW1rCk83VzJQdlFlZ3BJV21SOVVvYy90
            STVNWEhqeHZnOFdwV0xsVzVIM1h0aFUKLS0tIDVoM2ptM3NlR3dIMHo4bEY1TG1M
            a1d6YzJzWFByelM0cmYwNjZKNFBTcGMKaINZdsmAH7crgIpKCbtftn+mdbG1WBRE
            /+V9hCYR62ADuiasN1gyyYtRJSssaNBtUCyk8fWWNpKgKxO1aVNMzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-29T14:24:14Z"
    mac: ENC[AES256_GCM,data:wkGSNzB5LxbixwRLKl1awdUuraXtlIcS3EXano492UeKHASb6LOdleZ7bO0C1lqwnam2PL9q8q7Reuu0s68xWzx99MYVBK4+3xvzviKyYxEZhXQK+0SzA7AlsLT3x/8Mrv5HZv07hdaPA5EtFyNmmjWGttmn2ZbOK7lk7fsitXo=,iv:nrrI8teUEu6mXPPk/t58Oc/R/uoYxMdI6UpSHoFiAls=,tag:oJwb7DC8jZP5bfmVCQPCeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
