{
    "data": "ENC[AES256_GCM,data:2RnA+tjH82x+NOGvPq9RPghzUk4MMW0ZTKTe/4IS6bmT2i3EH738cq34zrc/xkyKGz57IY1q7uX5zdl4CeXQxc/QeYcmB1BaRKTFsAlh0SOKX0XqKYG6+vvgXLDK8EytK60AzOhcL/pLBFzOmE30HPEw5I3YpeODqAoX72oLPY9Hobv8xZNrz1qknFT1KRMISiGJiLj9ojwlgW3T1mBbNZwJjKCSVuwaIAqV+zYHkLbmyLC/gvU1XwQsmNRirhptNpqh3sY5QA4UNCjnXa6cEMLLOzN39c1M9pnrlgVZnHJsxt0HZw==,iv:ib5jQwnDuEUWNX8NiCrQtjYbUx/ef2ErQIfEA4ieu7Y=,tag:huWRKZYvqdLkftOUQ6L/Bw==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QzhHTFh0VTlNWkd1MXdu\nbk9pVnByYjV2a3VIclh6RzE3S1dyZXc3WENJCjlqSUx2dmI3aEIvR3RRdEJFdStl\nY3gwS3c4c2VsU1RtMWRLOXNwbmpMYVkKLS0tIFZ3eGMvNzlvS3plOXRhMkxWdmJM\nVVg3b1VPcVBaaXFWanpxYWs1VEhlM0EKXALKddAw404KkaFAX+poC+zuQJq2W8Tf\n3CQ+1Rf5Nkjm3uAFERT4T7PVNiFwY4HABq/ZXsHeRLTb/9yUVqf2Xg==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-09-21T20:36:44Z",
        "mac": "ENC[AES256_GCM,data:XODMqNEVOuMtgJIxskang6jhppNDnxc25qK6ccvYlD70/yOQmvOj8ptvIZ2oLXBAaNvAyImFcW8fKxDkJyUWgM/c9ZwxNeO+2NRI9O7kFCRvDaOktODbaeCA1HRsOVEl/La0MGY38ugPboCLrdSvBqgdW3YigSPxzyafL+AcIC8=,iv:J20Huep8QVh4bdULTRdbIEtX5VjOayU3w03MhlXkgoU=,tag:eLNsrKG0oHfuu7d0S51dxw==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.3"
    }
}
