{
    "data": "ENC[AES256_GCM,data:DTvcKW1mv06pkY11izVWAP8uJXAu11jBMbLzLqcBbvrTnN1fAWTvX/d8i76LXD92trEV6hSHTxmNQ0lTHnu3pxfarCYtS1aa+TqRVRt4S5Q0Uj6NbWOYi981iR3hnxskYbKxVlRVzlFL/uaMFzv7iGHIZ8+Uuku4mJuuPb4UPHrDOKnHWoJRYnNU2u3fY/Y2SZnmR/5dQRZ8YA1CZKB6tmgdk0f2Vezb0od/v3IDmWgTetlL+IHE07pFiy/0GonsgrNsW0jagNOYwnC+Bu47rRwlA5vEgjtESArLHYI9RLHt2gUmV8gPB1ZY3sA+cQysaig9zpLfRvNhxlW0eB4aCugrSLjHAxaq66wQ6AwMXhgquf02DI20TWxmVRXEi4o5bPY1oxd5MS18hG4sGMA9YdGCQkLBGFAfqgI/dCrYHAB6/Q+JxU5Wh/ovj6w2lIVMm0VV9iBsFJtDUf1rXzd9qcYgJ06ABKyFRDuBb2NG58iJE3D+SdhL6fx1igICH9I3ux7lQ7eWqtRfFI+R1G/GoSP6RNw7Ur/33kHO6avvArBDtS20OBu6dmWrHnE45GIYILJuvTHDTLvbBa001HfUi4U/+P5wgJs00IAhDchtiT5U947OQOFGI7y8XkI/vZd02d78RcuPUcpbfFAEm7ToIhe7hhbu/CTuUrWfCPWAEmvZjYmgMkxhZ0MJmly2pI9Lr80Cku1sVEKuvOirNacPx8oe+LRwOEBiref0ygWmcFOvBqs7J8HYc3gYIR7CtMj8r6fhr+9pJg1OZsZ4gUImm6wBhsrmdJycoVG0SCpGnAnib0PHOu9Q1gtdP9ClDIqVP3Ndw33errFHvndzdvT08OhWYyi4JCu2adjPS9wYz3G1qyQJIWwiaQBJKU9O4cHfY3JuaBmOsAhFziWsn7w+nSV27YS/9d2f+kPuQ3SwzH2MaSEecCRL/wybJ6zhBfk6Qvxlml61gQAvBPmS5upLQrLRknqigdhs6Qe0jQDunLEqsZYMbZ8xNUJX6vKf3F5SNH+ZN/YgIGfQYdhyjggdzZklmG53WCxTLFar5J13n7+o+sLiApSyIUQBTXXc7XMcwVjC+Sy4limZTCjzaSBLjoZx8IwXTvRfc9VbROK1Qvk=,iv:i7r/tjgq6cwc/yTnT2ZKdZydV+aDZWkKP5Sb9+uikRs=,tag:T8V6OqqKYDvfWTYtRfPlug==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb3BKMEVsWmFsNGlQc1hS\nMVh3L0dhNFBFQm54MkNINHBzQ3pJT2JHaVJvClhGSERCeUVtdmxiN3crSW1Fdm1w\nU2hoZUVHTjQ0YnF5TWc4L0I4emp6N0kKLS0tIGJvSGlaam9pY2cwVlFiTmN1clQy\nR0lFcDJQMHhFOHRuZitNQ0RaYnF0NlUKrckjS/HK2z4lolWOZ9tcwp9hajfSHzQe\nwn5U3QuLa5UAYeZrlBXdEjEYQi/AFoRF1BRNavAv1AJIVsVCQbe9kg==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-09-21T20:36:45Z",
        "mac": "ENC[AES256_GCM,data:OZdEXqcyarkVLCUiwY7Jg/JIabhzGM2hI/JMNBeXhXI4QaDfzY/Y0V0Maql74f1GqWo/E0LUdBH4OP0SHG1EXP2Wp0JlXt2W1UbO+rwvwFXUVXtYdIooKoZkg18/aTuA1vB+oWEOx2u5on9ED2BUtbt2jj58smcssbBNBd6yDLI=,iv:rJvATD7UQB2FWX94dj/ZoClCd5TezN2vYl1bdFE5080=,tag:+i9BjizY2Za8HFztdx6rVw==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.3"
    }
}
