{
    "data": "ENC[AES256_GCM,data:4UqJ6ANFfCMD4SEXd6rrsOv99h9W1itjHNVVwydnpvfdXsjj1ifjX5e6aoMeTAbzI8tc2OD2F1X47uKvDmV7K/aKlYPTORLEoLf0pfwuHqq1j/2CLOj349um2Ohfj9js89wnIt3SXEkymuN60JOujJLBivtlrngltuDshjoN9U3aLTcotgK7qzvI0eu9x1DEOEjSZ8iu4kEeGQaA/4KsR+2kskAk9JpKxZOv6bcG7MRaj/wiFxZ/mAZB9c+HxuX7/8z/wY5tSjdTTYPHMKPI6yMCvmkA/6WGNoxWty61CA59p2ym0tTi7arYIFDJXAIZ6ArpGA+JN+ANVCOjCZC9Ac9XG2Mz9gvOScaYbnHyibo2Pk91BCLJts/3Ecu2lgzvS6W6jHxeyr4VDBexvEjWkFx27p9rJ2vSxCi9JJQ8ezRvLVW1UybgRIwys8hroEmMgKrgC+6+eVcWaidhpNkJX6cgeBOqHjupl/r6raz3Y/RbDPN/6bZV71UmpwVIWvG6UqC6DPlhwxebpnEs2bUaC7dcu9SzpE3vmxrIltByP8Mo6StRrC3Aud1fprZwcOGm11+lLCXsDrr80809vcQVzs8D+aE2sVazMoXNMjJ+Z7x3/pFdtzJBGI7yOgd5bWnv1SqnTgZ1WEfYIZk1MHU9dKJ16wLBZfoaOgPQhGc7xYke5FHV4lfJpfkgtZFOyoRNfnE1KP2ALtz7A7Da8drOJ1CnEGNlrR3q2tkoL2AcT5Sd99YFjK9fsQ/aKKeNjV2JfO8iYavYqzCTLxjM3IfSwwqex6PgbkmPA6s+8UqLBFoJi4KP4papzkyFDvG7Py3ME5XaltV9zBGRmbmH7T93LMcK1nLJLFWBXnr/WwQyCT8ZWI2g8aJNN6X3ZK6QJaVK+q3PfBlfE1HWyN94BIRhLa7lG23+ucXpdu7dXwymKgJbznAY1ObWMOp+UVFl3T7HSqZnIzpMOVG/G8ABXj5H1xybdSA7y0H3JaqzUVVWjtpAucE8xMbuuqfQzvAysYIYhikrjOncxM2NECCg1iAUSnc05QFhgxSM9YFSVFtGDFLrRJXEcBVnBb533FV8Wk1fhAqx25+FRGhaAkx+a47eGr1jjyuSz+wlLP1N+jOLKQ==,iv:Etgx1rS+Y9uDMMvAjgzRi38iTuho+4U0lQRN2m08+pg=,tag:FmLuujlOaPTogGPQ222JnA==,type:str]",
    "sops": {
        "kms": null,
        "gcp_kms": null,
        "azure_kv": null,
        "hc_vault": null,
        "age": [
            {
                "recipient": "age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473",
                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMzRrcFpvQk12S0RKeStO\nUk1YSlZJZVdxdUw5bk4wL0ZwZ2V6b05EUEM0CnYwRjdmTmw3OXpPN1NTaUMrdkJn\nOGE1aWVndUtHSlZpT2hYZlBNdERRM2cKLS0tIDBrTmtvNmZteXBqV2pCWW5DRFp6\ndk9KblJJTGtiSUgzeGVqemo0Yy9RZDgKcAmKdvGKSUhIayFUhEOLSfSEUR2P3ie4\nJLiqmIgWFfmfgqJyUB1z6utBqiAqsyK0VLJYI1n7SdAu4/1rvKbO0g==\n-----END AGE ENCRYPTED FILE-----\n"
            }
        ],
        "lastmodified": "2022-09-21T20:07:58Z",
        "mac": "ENC[AES256_GCM,data:QaRGs2LULmwOkCJmnUSRIon+r4O3Q47lpGhuULe3eZhEiyFkMD3Q45yURgNS5zvd8I48icqNosaUnbe2mX7/RQ+H2EoVko+ezJ4nGGfbfDsAyWU1K/x6yJkLgD/u8bt6fznapY32iKE4YyKUetQXEW3PNnrn7ZmzLWl8HYm6uN8=,iv:XH/CzbgNksIPVAPqt6J01QAenk7hCg6yjkCIjWhz5uE=,tag:P/WrBGbBjqQ99ljBQt+Z5A==,type:str]",
        "pgp": null,
        "unencrypted_suffix": "_unencrypted",
        "version": "3.7.3"
    }
}
