k3s_agent:
  node-ip: "{{ ansible_host }}"
  kubelet-arg:
    # Allow k8s services to contain TCP and UDP on the same port
    - "feature-gates=MixedProtocolLBService=true"
    - "resolv-conf=/run/systemd/resolve/resolv.conf"
