# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mnh29pYSU5cLERKxbIR8O8Bu8HI2KiCCFw==,iv:ziST7Cx0BVFFuc9e7vReUlCUv15bsGm+z3SHtgSRGjM=,tag:4Bglf37Ew9+JgOQ6ZNsoeQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:IvGAkmGWYr5NTuGTXlDpeKchzV+x7TLWwzi49N15FSwnLa5HSw==,iv:NxmVjEVxK7ss4vwOoBmwS6NJgsm3k4rm36/wT2d3Dv4=,tag:9oxFDZffBWx576p8FlgcHQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:HcXl0T/0pyYh8KKz06GBOA==,iv:F9G9fpane1RtNuQ8MczHVCODzBIFmmAqu5W1IFulRc0=,tag:xMG0k45+iNA5jN+p1n5hmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cC9DYXI1YVJITUxqMWFM
            NFA0Zk5nSW5ONFpsZVJ2dTNYbkV2UG9Zd3k0CnlQdEpPMnN0bGFMeGNCN0crT2cz
            ZVZPaGNHRURDenByMEdTaUtnU25idGsKLS0tIGZQNWpNVFIwbE1hSEJIRk9xZmFm
            NHJEYVJ3STlxWWc2QlRWN3ZPVkc1WXcKc/HRkXV68QkyO8idwrE6hvDWImYw4126
            A22WJJo33k/2psLFhp7r6uxexYXbVR6jpIzQlRbzEr42mKRoTEL3cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T18:24:20Z"
    mac: ENC[AES256_GCM,data:REpZcloRNEgpfLBdtvZOo8/ScjYBkD/Fd0H2Ac0b3u5mVUv9HvuYzhemx3JweuJt17U0UiD09N47wJUKjlHQSMTXAU+ieNpKR2A8XF7Sj/fcSSEKPAiCap780AND3alkyJi5R4LmQW6P5SqCVd477K8IgKR07iUlxsyafLp68qQ=,iv:T7xjoxuy18aZvUdPcUTPUup9Ng1I7DGb/xEsgMDszYU=,tag:JvroLrWTFGKWZZ2WMdvF8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
