# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: default
type: Opaque
stringData:
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:o6+3tpgMOQo=,iv:kI3117U8EsGHpqvdr1BAkRlRoLlhSoFAmEGJOebgtSU=,tag:RXwyux4fbzPpyY/tZAq2Pw==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Z1Wkmm/0gZgQcuYEuU5lXsvOeERbx/r48jFQ3b2mz8jU53QU9g==,iv:0RMfenn8HnZtvcvCb2PaDquKI59I1WQhY2yFS0k7YLc=,tag:Tf+hvaLoXf9X1CgNdJ+gWw==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:un6JcWxSxClmHEu946rNTbCfCymqqFGlYzc9saBy2X+laQbYfUTvnvYQp128W+FtbFtvDJ2SuvLyceE=,iv:YFUhijJMCmoNjbtNHLBGzaElz9JEDKcikfXdh+/NUmw=,tag:gz2chPxk8VWGgh644ZNKPQ==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:z4S+hJmgL3v0GgobFmYiuz/d83TEepMCF6Imk+wI5jawcqBwVVBcgb99AHoFQ/34JmbP5bexmB7FNw89frNj,iv:JoiUFtEMN+UglsppPhSO/LGGJqv4V4afQoJIE48RUTQ=,tag:00vnD+KgzccyfDMaLAz1bw==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:rmApXU9vR8ojtfJG9ZVbPT5tUEuoTZvyThNZUvFvlWB7Wa87XMBw91BPgQHzRGT4s/YvTP6H5z1ydaHstrvnKw==,iv:1xOEj8sBBvCnpwUsmZGnnTr2zVnn4YaLWBTQG7+T130=,tag:lh7dGAYDbIJ3jSmdm9gjLA==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:r5R2G5KHWwOuxIKW+ZXo4UaIlYyU/rlyg4+5Scfvzdku,iv:NPbnQMM3sH9GVeEIkkHScq6K1moyk15RvEO4Pt6Q65Y=,tag:iAQpCYL5mTXTu3/7asQDgg==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:UG6B63rT+qPVFeO/G+5AcjbK7jCpnAfKCa61knHSo0+rZUradS+ocOpuK9ufNNqorCvDNhw84Sf6fuimjevdKg==,iv:0ra7xx0SOxD5JfwlHa4gPFvgJeo+iIMTJTiKkJNDz6A=,tag:07WhiulA7+mUFG8aQH1zrg==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:QBrtjko6WAWQE05geyQkSusjvi+HlHlNXAz6tpbircDdDtu+UMOR61qrCMs+13K/8QVfEMFVQQfKUPfjPdxN,iv:bD6GJu6LY25gJKaQu3L75OA/3X3MpJJo3tK4rbFIKT8=,tag:vBD5rVTc9GOIQ85njGfKeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdklFenRINFZEWkU5aUNw
            UDdHQ2orb1NJbGN0T09iS25RYWY4S1BTTXdVClZIcEJ4OFNldnhWMVZKWGRBRnFF
            NXNUU2hxN2NGUlZ0a0JPTXE3V1Y2eUkKLS0tIGd6UzQ1SU5uVFIzWFN1dzhaVnVO
            ZDBtQUlJK1c4RHpBcTE4M0N5Vnp6ckUKGmKAidsD+TuYkcLKRiaNkyas6xRY74iv
            WAPH65WzoqrqCS3x3si5V17fQR4SqzoBqcLh/GKMHF5yJl7uotB6Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T20:07:58Z"
    mac: ENC[AES256_GCM,data:fMAyds4Jyf4WKEBTMXReJtzaKms5Q2dTiK/4wHYkxsKixVkGy1K0xk0fS8GKmtmRIXyczOpwb5R7qbZG2wvTyO3CEejgBgJiffEXS5S7bSKkru4pk9cvyNVcOpqy8B+g8wDOdX2WHBPOu5tRsHaieyKSfoHxI3xVMPWpucKttb0=,iv:3DMo7Ug3OiHAEdiGzLGVl5Bapq6pCnTaxCmqTi5pLCE=,tag:RN+xZe+k/9Pw1YqXOZi9Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
