# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: default
type: Opaque
stringData:
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:7JqOjN/2Omc=,iv:eb0zBpZaJ1dLqTlAxPUzGkitAXduVV2A+1WaG5YX7/0=,tag:gdOPS9erggXRHZxbg5L03w==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:6w1n6Vmh0wlU6OsVn3dA3PxiBG0mDjVlnQ8JDb4iLcu8GW8YLw==,iv:fdSFLhkEaIPrgdkOHu3GkDmf3w6GYSW8Pr0Do/F6YCk=,tag:MMETOVdhGqD7shYKZGXVIA==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:CcOaz+kHCadcZ/qVKKQUEghDIFGwYa/1PKaLIa1Ew+CE0DU9XL+lr+FFricSv2qMSfQYjZIB4AY5NsDQM2av,iv:h5gj8P9Unnm0fvdrp1W1pmc4UV2ucALOgAikERLRIyE=,tag:iwvqceaJoR8+SWFmn9Qd8A==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:PcSxQxjNHeA/Kpo0ZZV2VUyixy3EY2apnHxRtc3JWmj4t1KwkIxg6dn0MAcMUI0eycfPeUQ0Kd9PzcCgZzXG,iv:LNbbDjClw4zRCd7wB2r04OTndA1e1OUKzEYNyun0N5E=,tag:tutALVz/aRL8X2jlIudzKw==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:kvt5IXcwsrVNoNOYVrGC3bbuyyAkTJyhKrpwIewhXgMzc4BsIzIZNiqvuJmnP012+JYhLqMY0W17mlE2Ig22rg==,iv:d2hYvthFOHvEuBvCCJXRHJtA9rTDynGdb6b+etBErUw=,tag:7Poj35h3e4+yT5a5MOemlQ==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:Y4oey2uV74JZd76ovJYXzjghPntNUz7uaogzvg+eF+s2,iv:BuI8StfjM+6wM9CXqVOIOayt63aNCTf+4to4dKW8CZo=,tag:CTyyHKQ04nd0qMbM1sGZSw==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:856p6Gn8B4aK2rkmsKYjxLt7Qp7wGW8qAzmMbk6OZrkw51YeO6lu0SCRE3xhuUEOhYLJ9U7Yx0LRZj4jb04itg==,iv:hx14xm0pvYrm+EHFZQr7y+fiQRRqY33WXtjYazOoNNM=,tag:VdEXrt/7G7u07942SSPetQ==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:K43JsNkqMIYdFXtTlweaMevQUVAbExec089mB4pBSgIbavUiV7BhpDUIyuS86sRXcDc/5ECX+MVb3cjaRXGG,iv:2ynyHbPkMNTJLsj/xQtsQj4QdIhzjscmKQSGudc06tQ=,tag:kuPqS3gFEwbGev3tlvrMIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL3Q4bXMvTFNyT1JMNWNt
            bFcyaXorTkZ3TFloaGZwdG5TaUtkdkcxbGlVCjBGemdVWHc3VkhWaW03WGozQWVD
            S1RNUUpQK2JpUGViaFphTTkxdU1EQjAKLS0tIG9hUVJpM0dKZEpCUDZRSVJPWUhN
            R2NvSllrQmU5dVEyQzVNbGdrOTNRQ1UK4ekJs6R4cj50LgOw9JiyhjkVrzw1g+0J
            8uccuGVodA8kt+oNDNm1FiN/LlWc3oyoqROF4duhGx1zZNC/vPX7BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-11T22:04:31Z"
    mac: ENC[AES256_GCM,data:8YGMRHtQE/uvEGmdbIB76uPPf0bve3sSt3DnuP11iZm0banxWMclY24IfUWRHk+CBdLCF8CmWDptRXMPzFGCDEdFfERuGFjCX9wfZx5mWrmcNm6zBocIc+lbyrTIpvBTlv+6ZI9u/z28IRH0nzsaCupTdJoe/3l3WDzP3oMBH5M=,iv:vIFSDgPHfigm2xqAHrjKE9a8cSRVSpWDhldbOJ7QBzw=,tag:v7IPCD6Ug2r/X7Ifk0xuAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
