# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: default
type: Opaque
stringData:
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:eWcroXW28qk=,iv:YSQQ07uizqZZluoJtatALqRdzO4xEue64+va/ix4ThY=,tag:azfyL0avRJEuCphGgn9BNA==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:yPW4CSb/nSSzG6TJBNEf1Adjk42VXqEEEJGZp8hLHeXfEOFJYQ==,iv:Goa4nAB6ypnwz8sUUEcXLuwF0v5Gsl+ZX8RKPlkoQNE=,tag:y7wRCD9vtnp4g83tzsS0Jg==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:8blZTZJTIJe/MhSuqgn+/O7QZoShgiJuZR9U+6o6nIcPMhjFMEHwpaNN3GmLKeFXU2wmCKkh1vKSpSs=,iv:mzbLY9v+D8+5x+a0oKTRpzBNFq8a3zCv/FhJr+SIOEg=,tag:pFuQxNJXnr5O3KzfSt0DuQ==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:WJg/zDhveoVQogf85NpRcT1KsOljekPbSNreKsyHHOq9MaTUJNE5BtLYOcf5X9IzoHJwfHHIupRnyBZWTbQC,iv:JOY8fcD0xCC8ESebgJAVG6jXJ7ma96ITpiwKgwuQzsc=,tag:fmvrWoyKfPv8QdQw/DG9pw==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:WBOuy1swYqCUKpzDU3L96rVeG13CbU0v/abOlWKZSdLcKBDCDiLQvjtei6gXfLf/mev130T27wf5EtsAKzNtmg==,iv:NDIhNZsTMIVhTNpZfRMWBGqcqm29MCHpizgDKrWskIs=,tag:o4N5Jub2NdilzEuJ26H/eQ==,type:str]
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:anr7eeMHcJRr/7ntMvOB3LcoZCUo/Hz7JY6j9mnGWLte,iv:T1qZ2MywAt3ATH0Q6T9fU7mgjaFQ1FJ+6RF7Hlt3vmU=,tag:+nugC5pQC1ajgV/YLyvHdg==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:AZ+ImaoH2CTOhgM3iS1KWTdljwlZIsJF0M7rPiIP8e+pN6/Nrsm+WhZHPnNs01S6p0bkhIgamfAx/M7My74i8g==,iv:eVHNi09KRII+TddjzMtL/ElyKgosHL2rdyq+ZlI+Hkg=,tag:ZNnb11yYh+dqe+FH3qvsfQ==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ENC[AES256_GCM,data:LPYQlCOe5hWOnVzFr6zgpAu6fivI36aX0w17dU7HHHy5id2NtkqY3COCRDAIThmux8lf3jr5AMhquKNrYSpk,iv:q22xWgy9GX3wAhrZqtuVyb7AonWrk//2mro6iFjBR+A=,tag:oOhN83V8hD5PXmTsQVQFXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSnUvbEpENzdsNUt5eTFw
            SHNVd0FGTEJLTXVTRlNkMTl5UkxDVHVjakMwCnVYc2RKd3J0Z291eFJMSlNIQVBs
            MEEzZ1RnUFlRMXoybTZlNE5ZckVzUTgKLS0tIElMMllYaTE5OVAramthakhyelk4
            WjhOa0ZhOFB0NHVHUlp2QXZ5aWw0dGMKa4KamlwtlmotyhVTCsSLBdRxKvSIEw6F
            sk9LiJBfHfrEVKG4YS4u2Hkvskq2huUVMCvwAk3wMI0jPSAo1gsD+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-27T20:39:20Z"
    mac: ENC[AES256_GCM,data:ciFEAXXtIbNnprSuisqpbZxVdh1rZ9lZ0ro67crBTmqKup3I8H63+MMw3zfEKBkHI6OIwTaBKg4Z6hLIWEy2oUuKcMV4P48epkXKT4HUjMTc2cdeHCBhldVxbus7uUiS3YSfvljrDBsz0yUDBdipcFt/pwXOrpeWF069tXq3VJk=,iv:HaKDe7q1Vj+Gh/cCJFgEcGaqylmAPPJ4vcT4inroObY=,tag:ntkb9iiEwl7/2RRmXR155A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
