# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:sQXPBYw52yVGJevIesmYH7EujLOWbtgff9y0H2gZhZKEY83DtA==,iv:srilMPkrahiR06VnIlALjXkucfSYawF/ijiB6QMIQCc=,tag:PsZpXZJRBitfRCzf55MIiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMDI3UEVBWnBPa2RybmZV
            MUJFQTg2aHpNYjRHUGg1TFBGYzh1eFJDY1dnCjJzMTVyWEpTUWJKK25aTk9RcytM
            eFNWeGE1dTlDZ3ZDQzBuM3kzbU95TEEKLS0tIHhxcXh5KytkekRLWWJSZVcvZmdu
            aHhUeTQ0ZjRQU3dZWjZhTnAyZmgxMWcKrdbMw1GcctDPYLABHmmjpjBn7ZPc8P0p
            tpUfwpZQPMw46lVw5Gxvqhrriq8v2aP40dJtueYGIGGOZjW9M7je0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T18:24:20Z"
    mac: ENC[AES256_GCM,data:phKDbKMbHfvB4LUPnk2rFR25nXa4t4VOHGOOZ6fJZdKGWidNs4v9FuM3toeMc0aY2eJQI3K9DQ3+YvWWLf+0hA7yqTacPuTxV9anIxZP9AEPERIQa/K1GPjYRwgoOfLKVzDjI0Y4+2bc+pQt4H81ycnVypvGqDZPVpX+JNu9cHE=,iv:X3jZBlVmWcDzdl/bdOAbFaGKGWsrgFKqOiHMJyDkldI=,tag:x5Jgii5u5tnjyRCd1oLJ+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
