# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:5oQ7QlAYw/7flZ+iGYPoqKkgv9SLb9TZwfLSR1AzzWRI3VjzXQ==,iv:EcYZbxnBlz0d5hThH1Xu+FInCd6P5umwdMhcFLGxAcA=,tag:Ldk0VPnkGZ43L826pRgt9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RUY4SWYvRkRFT0FzSzJa
            QXR0RERac1NzVFAxRUp6SmY3RFpBMm5COGgwCndlMlREaVZRQjRyYmhZWmQxYUw3
            QUtXN1VjRGtvYTVUcFlOM2hFQWNrNEEKLS0tIElCSWM1bFBaL25mc3lyUFduRWtH
            YVRlVTRWRmVVUXZOOEl1T3FCenRTcjAKglaCbGuhL/6SEHCwM1ZiQvFpeRi0F4ll
            QQjva+sJAz3dTxpx5yqRDAt4GVQ9KG6MvLm9N/FbJXUh96KVgeKybQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-27T20:39:20Z"
    mac: ENC[AES256_GCM,data:wMWjUlMBrvspjPEOAy7l9BPYi/ksbkGGc7nco/sXNtBPP08s82ZRTUhAR54MozUpma/VcdHU6eKV8yE7ew4A88wvWGgWfSUCRRDf1eFSghEjO7/UwUQ6BaTrw6AcaEsrqnf+ZvCMPNR4wS3X5cToK4zq+3yQjCmHmc/G+FLOdk0=,iv:uzijk6usSz0xjh4raQqQQA553z2ZMq8d1cphCi8suG8=,tag:61DpfDhCh9Hx9Ks2lXQ/rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
