# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:yMEYWGM0RNZ9UXa0UrgPP3sLLYQJJasS8UOXi1F1b0rzL7+72g==,iv:PcmcerpFGu5ab+2ghYbhS8L9+Ww1PN6quI1UlLnw7ro=,tag:adXJhpZ71Nx+PjxYUFbjig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLREx0NnZVVUIvRXIxdUsr
            MXZVeHhwOXNHY2JJWnlEbEFBSk44RWRYK0hVCnJ5MGdFSDZtQXZkWnlaeEVTanNF
            OXJPNS93RlpoMFpqaUVvalRzMFgxczAKLS0tIHFPdTljUnEyQ2w4YWVac1FkSHM4
            ZUVZVjQvK1hCS1Q4ZnZWaHFvZ1BZWGsKzseI4x1gGyvd5V7H7kENbba+DqFdDzKu
            G4M4mAXPQQydE/AHf71n5gnTTxwirzRLrbvHaYarp6K/47o4WJ+tXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T08:45:02Z"
    mac: ENC[AES256_GCM,data:UOmkmygEX7YYIa+bQKtr33J7WAsG6EqYbKo/plHz2ZKGeYxX2krRNmsFh66l0heAQE/9kXgKGLeYUzeKeGgwrrJ9ZrQl8W9GyS/o7ZEkv8Z2WbYCCxdX2C9VSwQXpA1sozreoA8up57wLYPmhhMgrWSL76ckL8axc3/BbPln5Co=,iv:bufz6fCyGmamFOd4sGSF3kXdR2gL32EesTXP0qiHgD8=,tag:W+8n96JtXkDf3VQzOlMr+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
