# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Y1C2JhX9RgthoApmYtBLSR3TIFAoeJGn4w==,iv:9ow4kyOS+2xLF5X77H/bh7SAOKMIbbXH/SKdPpfAMEE=,tag:gzBJWUW7N51Gz2mr5pHWOA==,type:str]
    api-key: ENC[AES256_GCM,data:LJzlM9XKHxy0O2yaOgb9kJ8WbgHb4hBYXKduzX5NAL30T21UJw==,iv:SfoFOwYTOZrQRqha9bV5qhVm5rmMCC7HxduXl/pkJ5M=,tag:vGP3w0T0Qp1CxiK2LYhw5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSXdBOTRNamZLVWpXNWJp
            ZGllZklzM2tSRWY4RjkwZkZkeTR6WlA2TFQwClJOd2ZrTWRyMCtxdjNtVnYyYlNI
            THlHd2VrRGdRT0hiK0xmNGViMmYwY28KLS0tIGlvb3prZnNPVTlyb1dNUnVLZlFQ
            TEZFUElaMGcrTUxZSHVUeDZmbE1mZ2cKbWrJaY7I0slTlfpGDZNO2OBpXMxDJc5/
            4jEytC87F2ysmZJaEbgFIcNYcQc9JBWknmHwFWIF2Gc8bvAA+m9rSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-27T20:39:20Z"
    mac: ENC[AES256_GCM,data:qHxjklN4svEzUrvfPGn7S8247GrAOPJU1wYTa0SYth6mEU7yGkfNjnM/4n53mt+HRjk8hYXyoKULowsLlhqnTiLeCDbd4cTbcmrgDX3rRnbkcwcEkRbcz+6zPWtB7Awij4fYHN06opkSFJAB6Dfz1iWtGRMNeZyWvlMGf/CAtuc=,iv:4heQJ6GW+v+sfxlYG+BkMGNqf6MaZEIEDdy3KW0CeQA=,tag:tm+r+qw9Bl+nIh+HlOJRrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
