# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:lCu+SK6aQXsBSXeP5hRzTScjGuw3fplLCA==,iv:5ADmD1MEHIWHIOXkgLkY9/NxNbKW7sR9SvomSOYHsBg=,tag:ZxClA52oZo8bVECXvPs9Pw==,type:str]
    api-key: ENC[AES256_GCM,data:OoCDCpovTKqdJIi4NzcwUY7ZzjsX2YTVxrrvNKtilXSI18iY1A==,iv:OrttHtSmbbGQUH70pCYAYtLs5vIgi8yF9CbR80wuS1o=,tag:cMOybc1Mao+ggL6fdKAFHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd2hZMWxvNVRyZ0Nna1pM
            T3FzTXdxeXlVcGtGakxyeUdvRTEyMWk4ZjN3CmVaOVpxNllEMTlTdjlRTmFQV2dT
            RDdxQWYxdUtMT2pVdHpoOXVjeER5Y1EKLS0tIFB6SGltOHpJRnFtc0pnbEFLTGE3
            S000Z0hJQVh5UWNrbWxvWUcvQVhWVFEKR0H/GtOM0DYh1H07sZgPgQBSZRfCQFD9
            rim/PkSbptb5u3nvNmnpjkTzXOS4cNUE/KieM/efAyrBGMI1r286UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T15:37:54Z"
    mac: ENC[AES256_GCM,data:Z9B61qO5plVZFOg20yhnilUqyzv/okuMgSjlR0mh5iNgiU1NtyIuYnBtn0WRpYSwu8StxTpgo1rHtCoN207kiWtHMbMGpewHlW3cy7+feYCq7k8BS8i5dR0HGh2BWS35LupTMQr5zAuCoqIj7dsO1BBExadLSFM57bPvxviQcvI=,iv:U4RlC+fa3J9PK0bZr+lPwLvmjxnrq+z74F3zuuTwxH8=,tag:Ph+eG+Zb23tvyYUdFyoIBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
