# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: default
type: Opaque
stringData:
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ${BOOTSTRAP_AUTHELIA_STORAGE_POSTGRES_USERNAME}
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ${BOOTSTRAP_AUTHELIA_STORAGE_POSTGRES_PASSWORD}
    AUTHELIA_JWT_SECRET: ${BOOTSTRAP_AUTHELIA_JWT_SECRET}
    AUTHELIA_SESSION_SECRET: ${BOOTSTRAP_AUTHELIA_SESSION_SECRET}
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ${BOOTSTRAP_AUTHELIA_STORAGE_ENCRYPTION_KEY}
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${BOOTSTRAP_AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD}
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ${BOOTSTRAP_AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET}
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: ${BOOTSTRAP_AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY}
