[[users]]
    name = "svc"
    uidnumber = 5000
    primarygroup = 6500
    passbcrypt = "243261243132243542554b44744b4b534531333941694e355a687033654c6b62504f6879382f374566446c396742682e6258684b6f4e6b5874393671"
    [[users.capabilities]]
        action = "search"
        object = "*"
[[users]]
    name = "admin"
    mail = ""
    givenname = "admin"
    sn = ""
    uidnumber = 5001
    primarygroup = 6502
    othergroups = [ 6501 ]
    passbcrypt = "${BOOTSTRAP_GLAUTH_USER0_PASSWORD}"
[[users]]
    name = "${BOOTSTRAP_GLAUTH_USER1_NAME}"
    mail = "${BOOTSTRAP_GLAUTH_USER1_MAIL}"
    givenname = "${BOOTSTRAP_GLAUTH_USER1_GIVEN_NAME}"
    sn = ""
    uidnumber = 5002
    primarygroup = 6502
    passbcrypt = "${BOOTSTRAP_GLAUTH_USER1_PASSWORD}"
    sshkeys = [ "${BOOTSTRAP_GLAUTH_USER1_SSH_KEY}" ]
