---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Stockholm
  METALLB_LB_RANGE: 192.168.210.75-192.168.210.90
  METALLB_K8S_GATEWAY_ADDR: 192.168.210.75
  METALLB_INGRESS_ADDR: 192.168.210.76
