# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:66rotslELDKFlwk=,iv:9EqMUHDuzQq88TnIOg7CryCJqu9mocLcIPNYkX0bO4k=,tag:r6R+6sRjJTOdug4Mc5kppA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:VOeZg0pzUncRooXQk/dxd4hI3C3frw69Yw==,iv:snYLxxrG4FaG3HvdtjAGYMVJJHR9phwwtpGgekCHLZk=,tag:yAQori5Y2sh+8q80w9QIbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZnR4b05Hb2V0RzM1ODk2
            cnBXSkdlb2taRVJEbE1UcDlHUnZ1bHVyd2o0Cnl6L2NqUlgrd2VnamIyU1FhRFpy
            VFZYVTFxTU1MSGk0NTlML05VaHorQzAKLS0tIFp3Z0tCdnJuRTV5N0lOM0ZscDRq
            MjJ4QjRIQmtFbFNTZWpWbll0MExuTGcKIYfzNI1YbbAzyfVhPaacEX3zMi6GMmLp
            Wcp7EKu2ylzucNtotA5C593ETJOeqI2/KBQFezZm51a2kxl7oTCaaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T09:18:55Z"
    mac: ENC[AES256_GCM,data:UvAF53ftinzc3E+69HQMTYO/g1GmxkoYnzXG+z4ytojVonrWiMwxz2TF2Y58ah65lPE1C3a3oRsLa8G68iyu/bqmuWMA/vgE1Y47Esi5vcmWUaQZ2UcueRYvCvScW0HrWHvTjOvZeEdTAWqgd4p6weNGoTzlY+5QeRDrGSs8FS4=,iv:Nlzof72u8LQfQRnRUuJ2KonJO5VST46ASHR9laEdDGQ=,tag:SC18vVz22gG5E8FF2K/QAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
