# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:8jxwqAIy5DbWEks=,iv:ekliBFNJduZRY15LFlcbEUTLw9OYfkTon/9iPWhFkzY=,tag:+l+L8A1DzWR0fD/N1rEIQg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:b8Ui4OGcXzSD9BSb661VZBKnU+i4twnrmQ==,iv:tMjtJlxYoO9i+5XlsVXfXB2OiTNd1jzBPbFFkRGs3Ek=,tag:FzItnVg1ldiT5ZsYj6pShg==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:ZVQhvqbW5TPCggg=,iv:GlxQ/07mG0EPv24NQX488LpeDyzgC7VYukblmwhQTGI=,tag:vfaE+J7at0bZav4uLP31fQ==,type:str]
    SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ucjOA+VcqEN6dn+nPHhIeS88yiedqjZXUyLG59H3mhpzvuKzOXpl3ihEiPsqrpJmo6Lp2oXRZU10V/K7nRDNlpqSksQS88PoApNNcMcqH76eZELIuqfmFpWDz4eF1iWAKzuGqHARKlgU70aGoU2yKFX6wZS6ymRGnfKlqwk6iveKrciKC/oDU9BXmJuMV3QVtv0NYMqODUUL9nPsgd1e3orrt2d8U6mUd5fS0qup/k/RfgX7ZQsARMvyfnffXetUi2Wtp5G9pmtdi1ELbOMgYXeYHcsD+A2A8IZf9QBT0j7I1htmc6HcuhEHv/Y6J3OQs2/TEUcmknmxQbeLb27wPQ==,iv:p5muyVSMXymXWVf8Ej13IAep50pPz9EcqO1GH0Z8VPk=,tag:Tn0lQpZUDTogl+gRhtyXrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWGkzSkxhOTBPd0hJYjN6
            Q2JEMmpzbXljTGNjcVlQRUdQeHJwTjQrbkdFCnZscVlIQkNPNEhvRFIwTkR5dmpG
            K2NSZmgrZmx1V2ZHYjh0VTVzdUdDNFEKLS0tIG1rVDYrVjJ3UFBHU2ppREZXL3hB
            YTkrOEtkRzNiVFp5OVRUZkR4Q0ZLblUKw2Y7W2WLX8wPux+M0dUnXhW2YU5v6gZy
            7yqmArYYY0aN3s6dJUHdKJ1eZv2PF6yz9MaPrrXCrWwX9o2hqNmBUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-14T20:59:12Z"
    mac: ENC[AES256_GCM,data:sb1RKuahZYS2sqb3K4w/Pwx2DP9MTg1BboSdJdS2fK0ZKoQBvDJ3ZefmoGHj9gkcQVxnDI4pLX/9hCQFjCtultbz6Cxb6hJ02p97ttcXmjdlK3zPfbYuwCg3r72rNwlnPk59BWavw0w3YOWMF0M5/lu2dQG3wyoxsQzksjhcP9w=,iv:bSSyuXXpig8rxrrw7zovo8VHrqJw1+BCp2NNlYqc3nk=,tag:8n8Y5rllArbRCMtR3h+gIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
