---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-app
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./flux-cluster/apps/databases/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cloudnative-pg
      namespace: default
  interval: 10m
  retryInterval: 2m
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-cluster
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-app
  path: ./flux-cluster/apps/databases/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  wait: true
  interval: 10m
  retryInterval: 2m
  timeout: 1m
