kind: Secret
ansible_user: ENC[AES256_GCM,data:XQ64rqo=,iv:StXl3R/TLitdc1t2tdyhkqUGX4xvDh3YevSzfdr6RLg=,tag:vfuSxE3l8dmNHxfpnGzTsw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:j0D5HH2bdQ==,iv:lbQBY6kLvJb1wOu7e0cKrEKRu23Fp+KTC67oTB+Mrkk=,tag:dx77H2dq++dNDBDUZQC5Dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdG12andsOHF0MElvQUV0
            MzZ1RS9EU09iOXJtbHZla0R6WUpiV2IzTDIwCnZwNjl6VS9seS92amtZT2Z0dVlx
            NFdrdTBKQnYwN3Z2SEhyTVBDclJhNDAKLS0tIFg1ZXBCNFNSZGNmaHF1cTJsSjJT
            TWtEM1ZWUkVGdGpETUs5WGYwTkg3bm8KzrhJMcMUvzzF1KT9WNXzJ4DD/wEkuEJA
            UFj13yWE9ERvIqjkhJPG4LbDy6DsbbH3sH6cqfLZx8/rjhtdojQUYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T09:18:55Z"
    mac: ENC[AES256_GCM,data:lfuhArtB2beOa5W8xyCmQDjjgUws0pA5UabzzLqLJbUAfD0zI0bNaqIwOb81sxPgYKTClo8qD6SbOHAcITpndhreiFXZokZz0kxwAQMlJ+ZrUbWzxnFtX17ikkINAtIWpw2qwD7dP1wPOpQOVzbj6rfT84H2jX1LxwhNDf2zWho=,iv:KRisXh3shy9ywFiJ253PFDOoV6yuUamnCPiqiQ/KOBc=,tag:K7jIAoxsvR4SFdRR8HTgBg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
