kind: Secret
ansible_user: ENC[AES256_GCM,data:p8DttVE=,iv:GjTI6ZDIdXdlk5pQ4BGquH+Pk/NDh/sTO1C/BppCoak=,tag:g7BJsI/tR15cfHj1C6LDrQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:MYUK1pL73Q==,iv:PHGYZAIVRtjznkUlQAjUXPeYyPm3LgcfjZ/2LseCpTM=,tag:CfmemQ4dWib8myp05bj49Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZVpCcGxGUSttQ1U4NTV3
            TWFYRHlIUzUvN28wVGdkUnRMenNkTkdaazI4ClpIMzdrNEFIM0ErY2todDdiV2g3
            NGgyenZUSkliUnJrZ2YzbG1vcWw3N0kKLS0tIHhON0JrOTQ3MnRaeXg4ZiszQ3NK
            QmxrR2UrWnhmOUlORWNDMlBoc2VKTncKtVYK0YHmuy5/0LuqwkZawJTzfGarqfU9
            4rQYU0giUBnm4ETvxOBROJLd2GOO1lWshPct98J/iqGGB+zUxi2GsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-27T20:39:21Z"
    mac: ENC[AES256_GCM,data:u001Ob6L6HZUwmMJnWsDLXkeadRcuEtLBBaStdS7QUafjVQJH2wg/C2DAuA/YBkhlw6OS1dvgoO90mtVCyo1IAHrgA6I33FGUGfL0B+uH73BAGybyc+PmKdiiez1QNr02ckoEeURoYXFyRZxGipZshm03p86U4f+BDMPybj/Rw4=,iv:1ixNwcjYSspIYuvbtn45QAT0S3rSeLO9nVHmYzJWYCs=,tag:DL4RBxPKwtzVCAObVizXtA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
