kind: Secret
ansible_user: ENC[AES256_GCM,data:dd1SzUE=,iv:VUvR+SW8hm+qb1RqsB53z38L+jr2/Ifncz3mM2UTDoA=,tag:2urvjGjD4J8LropCmXs/Hg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cXa8dne3ug==,iv:0Qh3mOEY7wVUT3TC65V3+G1r6JXLnympiL7b/D8+N3I=,tag:VwKocu6Vhboh1TdNlhd43g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWVZERlBQaWk0K3dkNHlM
            Q2R4RWJ4MTRkVXN1ejl3bFBCay9Yemoreno4CmkzaDhZK3RXNHB0LytVRjJnVjFv
            R0V4aFNxbmxyMGJCVFRaemdqTWFiZ0UKLS0tIGpZemRIMVBraC8xNHN5VFNGZk42
            V0VnQ3NxSjJNZUVsbG1rWm1xUG1ZaDAK5VPBwhn9rACNA7GtgyJWHO1gHrau12aF
            GpSDVxbF5+fXTgwJ4uMIjD3xQuV+CZHe8k2jRLSQrZGmqZFlHIQk+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-03T15:37:54Z"
    mac: ENC[AES256_GCM,data:5YBV8lR1ZBaLm7JdWrNJFAeuafAlP18MQWs0xJ1V0UTfSK5vJMvGofWYDfuxktT2mAJULIOXAry/TJrA14F5wb41F5PoaxDWo8lCn6GlU0HPTFwikXdRsD4Dka39ptAy/GPJSsARPvuGhn0pD+9HqLt1n0PV33CPKdsqaD/M9h0=,iv:6my3Of7c4TB+5AI4WyadAS1810deReWo5Q4gUBuU6YU=,tag:2YDR4iyq2PQ3p5E8kXi6HQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
