kind: Secret
ansible_user: ENC[AES256_GCM,data:vMXJiyg=,iv:TZWfPB45AF1I+WAlAimPNY9Pf3Jmuxg/E7+ZI9tlqvc=,tag:8lyqKMdS/k2dxxq7DOl28Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:KNBluHjyXQ==,iv:PYURqCgPMTdNgAH58rkXm3/wj/k4/SZrmlUSraLsY+o=,tag:rNxPM2GKUxO6bH3yJOG+Ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSG1pU3NDZXZtbzBaN2xL
            MEVYVkxpemd5bE9NVzlVY2FVVExiWGhuQ3hNCmp6Vi84UzUydzA2N1R4ek9adm91
            SE1wTUwyVVZSN2dpOHl1TEYzWEprS1EKLS0tIDRIWVRKY09uM0NBNGxmOGJJVnp6
            emFkMEx4T01kYVhTMGVxbXl6VnNDb3MK/kaEfql2WV1qQcKomigBmepDmqiWyC9G
            jOYgR/6t093DAp/yPTjmYIkklAo/0tNvOwRHbuEfV12Xqg6Ys2X2Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-27T20:39:21Z"
    mac: ENC[AES256_GCM,data:3fRCT8sW3IXD/VbGaNygynwbv7zDugG0Peyg7NWjcvykGMMIKhItcWYIMlAKAZmfJhfxROMq2LhYdIbmzZbH5ObjnS6zo3tdyODNi7DHS/neJd2s2r2i6uwdDJXTouLHR0DxuSMBf21sovG/x1CMA25q4BuavWWNdtrxX3qjGN4=,iv:sKdhkr1+8nGYWzr0zNnWF/MPqVaZAdz6IB8Thp1tmeI=,tag:UfVSmzBF8kNtrBP1QdOJwA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
