kind: Secret
ansible_user: ENC[AES256_GCM,data:YcsqWkI=,iv:pKHKDyhTAslP9b2Lo7ta/X/4Rg9EzfZfXPNJSCeJ6+M=,tag:13ESfnUuhbnnFR4mR9mgRQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:+pysgXxYPg==,iv:wr8FUh0OBwofPGSt0UU5ArnIG8Zx6AyD7hZ8pPUrkyA=,tag:E3nwTFms5TfXotcjQ8EItA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYm42TkdKcWN2R25DSlIx
            VEtFbndKZFU1dXgwZVNQMUZNM0pIUk9oVndrCjBMV0lHSEhqbkl5TEJQZVNjWi85
            enIrSXZVU2lYWUhQeGIzWXNybGh3TjgKLS0tICszVjhtaENqdFdTdzB5eEZzVElK
            MTVtUkJrU0dFYlhrbGRCM1pxWnhJWlkK5JIsaQxa8sPyxXFA6ALC4/L3hxVqCYCH
            dVLpDshp27qKdld4//HFfa1mSwFTVZSIr18nK6+lkJmRhGFF/1XWBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T08:45:03Z"
    mac: ENC[AES256_GCM,data:ZvKWAaZQabEebKVnCn4vMTHNDx90kHORuLIrAQHcJ+TPUjpAahpNjTbCwS+k3I4yREFNju6LHzJBelxpfmqWqONo1MogIa5dDKjrCwn6HDwhJ5Sm6NWvl3k1yVgrlCGRGdMgyehPV1Gbb813yDP9F/l4jlbNw+fNSfKOE3GBGt0=,iv:9ixtAlHRvGUeQups2kaBcU5FIGsWPWSz10U62BR81G4=,tag:5RKXWCy2hrhZ/VA0CC4ZLw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
