---
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.default.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.default.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.default.svc.cluster.local
          port: 26379

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: ["flux-receiver.${SECRET_DOMAIN}"]
      policy: bypass
    - domain: ["*.${SECRET_DOMAIN}"]
      networks: internal
      policy: one_factor

notifier:
  smtp:
    host: "${AUTHELIA_NOTIFIER_SMTP_HOST}"
    username: "${AUTHELIA_NOTIFIER_SMTP_USER}"
    password: "${AUTHELIA_NOTIFIER_SMTP_PASSWORD}"

# identity_providers:
#   oidc:
#     cors:
#       endpoints: ["authorization", "token", "revocation", "introspection"]
#       allowed_origins_from_client_redirect_uris: true
#     clients:
#       - id: minio
#         description: Minio
#         secret: "${SECRET_MINIO_OAUTH_CLIENT_SECRET}"
#         public: false
#         authorization_policy: two_factor
#         pre_configured_consent_duration: 1y
#         scopes: ["openid", "profile", "groups", "email"]
#         redirect_uris: ["https://minio.${SECRET_DOMAIN}/oauth_callback"]
#         userinfo_signing_algorithm: none
