---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  - ./default/ks.yaml
  - ./flux-system/ks.yaml
  - ./kube-system/ks.yaml
  - ./networking/ks.yaml
  # - system-upgrade
  - ./authentication/ks.yaml
  - ./databases/ks.yaml
  - ./kube-tools/ks.yaml
  - ./storage/ks.yaml
  - ./monitoring/ks.yaml
  - ./web-tools/ks.yaml
  - ./media/ks.yaml
