---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - default
  - flux-system
  - kube-system
  - networking
  # - system-upgrade
  - authentication
  - databases
  - kube-tools
  - storage
  - monitoring
  - web-tools
  - media
