---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-cluster
  namespace: &namespace default
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: postgres
      namespace: default
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    resources:
      - apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: postgres
          namespace: *namespace
          annotations:
            kyverno.io/ignore: "true"
        spec:
          instances: 3
          primaryUpdateStrategy: unsupervised
          storage:
            size: 5Gi
            storageClass: ceph-block
          superuserSecret:
            name: postgres-superuser
          monitoring:
            enablePodMonitor: true
