# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:Q2lw6Yrftx0=,iv:mEmwnnBQSt5U7IfFnvafW/x5zN91L0PQiyhxUsn0aiE=,tag:Kl7+D/u5mv3UbkB4GAkZYQ==,type:str]
    password: ENC[AES256_GCM,data:e82eY7plMHddVT8xLtw=,iv:SUxPleoK3lSSs9ha+Riu3R3Bu4kbWRGiXWyf7Rgalz0=,tag:VB5ZEFUz6U5yh6yMXDClFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBselUwYVM1aGQ2a2VqUmNi
            aUtRRkdaOTdFbHhwd2VaMitneVQxTGx5QTI4CktVSzNsNXVKWWtIMm52dkdnY2U0
            L3JRem90azFHM2V0ZHJLd2FOYWdKQU0KLS0tIG5GTk9HTFlod3dLYVRMbzdiOWhp
            RmQ2YitpYmtIUkZhdVVkT2R2dlcwdkUKDz/W+amnCFd8LsEBYmqsJkI+DszkCXte
            /sROJCfI8GT4pyK3YlaDkvv3/j2SA0/GQKjEyGpQkXs3yP5fCDHhrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-12T20:31:22Z"
    mac: ENC[AES256_GCM,data:rdmqWNa6jMCBDsCohOP4fgusvAL5UVxgEDNCT+GHsg7YRfTmn1iqodBrzbTYufVnqWDqdGrxUgugYnZXMzIJu8jzwuQmWx3MBdnR6tI12DJyT61ihCMO+o87384hh+RFHUasusmahEU9dqQAgRqnvJC5xI8MT/8S9ah28Wq0Zos=,iv:IcvziEKd2AyJWj6v3afVk0QvWauQI4309rGkjMNrLYg=,tag:kb5ZmHRHcRzmB3w2bTNHhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
