# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6qN+8oStVsw1QYMP5WvhFE8qkdI+bEQaLLZ9tylfn9ND9YB2+1CfVw==,iv:wAaeJwyqjA75pWuXJczVFT/+XioQxT5UBjnSUYD541E=,tag:iKZnKeG0W81n0tkLW1eLPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YnQ5eFdNdzN3Zkd6d0hL
            TXRKc1BlY0w4ZmlqOCtkMWFJck44dDBHbWk4Ck13QlR3REVPMS9PN0ZtTDVmOHMz
            T0xDUHhSWGUwcExTeCtSbnRNZk1RRzQKLS0tIHR0RFRTLzJNWnBrTzBvU2N3cGZi
            UXhMRjY5T1RsajJDaTdjbUNveTlncGsKR1XShAuO3F2d6FKhmyAFHcapoAb/GZ+c
            okKA1rW2Wrcw2Je0K1v5l4PclM4cDpyNHzeua4It8EZA/F6un8ho+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T20:33:51Z"
    mac: ENC[AES256_GCM,data:nkfPsXUh6u5LAw/C6VvfC2x9YYSopw4te40O3R22+2TeyZ+/qNR1ERrK/ukojMSjA+YKetafluhIxvRkuhYRLr5PDwdEU5IUfO8PoNvHQxOOaV2RslyFFv0424hKb//F3FMMg6Njk7HpQEbOiKJP6/HonaaCVgb4NdjiBysTzqE=,iv:Cia1OQU3sMPt8Y3a5XGU+3r5N618mpdA0+dAeo4MMnI=,tag:0BTTfdgqCS4YKXIi2MgTXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
