# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:QcFYXSyw2CpX09f+WUn5Rci3oJhZBImU5/47oJBx82k3rpzDjC/whQ==,iv:exEI5cJyEW7y+CdsXvk6BAmr8vC/3+2h3sVUq1ogvl0=,tag:iuabjmstwPa0S5orl9B7tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dqeu2hqrml7n7zyzz4vxjhk8rjt0wm8jqennwmtvej3sd9dhcsysl5z473
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXV1lFcE5pcXhsZkdUcTZX
            ekxMTFA2R2I5a0M5VFZXaXZ2SStmL2JZbkg0CnVwekFQV2UwS01TL2kxMEZaS2xi
            ZGllSUNDb2orWXlzV29FbTU5OHI3V3MKLS0tIEZvZHpFdmFjMjRJaEYyMnpQTGZl
            TVFaZHd4WWVBTWhSVEtEbGhUSTA1NDgKnc1yvS08u2g/jGQhfaafRsk3kHNyHWDF
            P1svxwRAbctoJfU/xHS9KfNEKA50ETbN5YQpaKmq8PkrQLE+pf5SSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-20T18:24:20Z"
    mac: ENC[AES256_GCM,data:tHRx4i0WQ0bBpJ/T6GnP6Xw+RfO4p5Hau637Jm5FJwth5AM8+c7dkXp+LfTJnYybjgr4DiMKHlk4rsUOYjQl/smaO5J5YVqoQ80u+cWytxF35dTSOkfek6mz38XZfBUk0LZYnkebLQPRveVqHB7iAATvLuwxTU+qavNCIy8yo4s=,iv:7FM+iEgbGzRB4tql9mLmvnWC0iMdO4bZWuRhsNs7jOk=,tag:nnmlUmuX1SBjFIcfTWEbbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
