apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:McwWotXYFl8=,iv:p1PL1a1Mg3R/OvwbQf+raE2RNK9UH9KxyYzdZJ6zO7A=,tag:2RBGJ3nwwfBXWg0YvT3KCA==,type:str]
    password: ENC[AES256_GCM,data:jrcvjLXyAE1UhNnsvxeItTceOutz+5DB1Q==,iv:2sHQVuJhVDC8boiCXVZBqt3T4JuNEvJwkshd6b594/0=,tag:N8gAu/dp3qoXkbuPGRoXxg==,type:str]

---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: default
    labels:
        k8s.enterprisedb.io/reload: "true"
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:OWJrAxtFI/UmfA==,iv:nQX4XX99PBWngbRD7cP5tvPGiQXPHGatlCxeRdeazok=,tag:K+KS7xw+J2noWxcy82spbA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:8Mo8ZwRcAj1XKR/mxSlxK251RolrFgCfzWIA,iv:GLHP1UooFpiOAJqG7Jd6k/6LlKvyrzcItSpLRdRI0FI=,tag:VLRLkkY/u5iq0MTYR2IRyg==,type:str]
