# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ${BOOTSTRAP_POSTGRES_USERNAME}
    password: ${BOOTSTRAP_POSTGRES_PASSWORD}
