---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: default
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true
  storage:
    size: 100Mi
